name       : haskell-hans
version    : 3.0.2
release    : 3
source     :
    - https://hackage.haskell.org/package/hans-3.0.2/hans-3.0.2.tar.gz : 49225eb6acc01f044a37e7e874e0ead5d03953ba3ea99acb2d02f5d0f694f591
license    : BSD-3-Clause
component  : programming.haskell
summary    : HaNS is a lightweight, pure Haskell network stack that can be used for Haskell networking in the context of the HaLVM, or with a Linux tap device.
description: |
    HaNS is a lightweight, pure Haskell network stack that can be used for Haskell networking in the context of the HaLVM, or with a Linux tap device.
builddeps  :
    - haskell-boundedchan-devel
    - haskell-cabal-install
    - haskell-cereal-devel
    - haskell-cryptonite-devel
    - haskell-heaps-devel
    - haskell-monadlib-devel
    - haskell-psqueues-devel
    - haskell-random-devel
    - haskell-sha-devel
rundeps    :
    - devel :
        - haskell-boundedchan-devel
        - haskell-cereal-devel
        - haskell-cryptonite-devel
        - haskell-heaps-devel
        - haskell-monadlib-devel
        - haskell-psqueues-devel
        - haskell-random-devel
        - haskell-sha-devel
networking : yes
setup      : |
    sed -i "s|0.3.3|0.3.7|g" hans.cabal # heaps
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
