name       : haskell-hans
version    : 3.0.2
release    : 2
source     :
    - https://hackage.haskell.org/package/hans-3.0.2/hans-3.0.2.tar.gz : 49225eb6acc01f044a37e7e874e0ead5d03953ba3ea99acb2d02f5d0f694f591
license    : BSD-3-Clause
component  : programming.haskell
summary    : HaNS is a lightweight, pure Haskell network stack that can be used for Haskell networking in the context of the HaLVM, or with a Linux tap device.
description: "HaNS is a lightweight, pure Haskell network stack that can be used for Haskell networking in the context of the HaLVM, or with a Linux tap device. \n"
builddeps  :
    - haskell-boundedchan
    - haskell-cabal-install
    - haskell-cereal
    - haskell-cryptonite
    - haskell-heaps
    - haskell-memory
    - haskell-monadlib
    - haskell-psqueues
    - haskell-random
    - haskell-sha
setup      : |
    sed -i "s|0.3.3|0.3.6|g" hans.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
