name       : haskell-hans
version    : 3.0.1
release    : 1
source     :
    - http://hackage.haskell.org/package/hans-3.0.1/hans-3.0.1.tar.gz : 24da2418908a3297901c8b7e273b70a44a6b7255659de31b76afa4e3ffcc57ad
license    : BSD-3-Clause
component  : programming.haskell
summary    : HaNS is a lightweight, pure Haskell network stack that can be used for Haskell networking in the context of the HaLVM, or with a Linux tap device. 
description: |
    HaNS is a lightweight, pure Haskell network stack that can be used for Haskell networking in the context of the HaLVM, or with a Linux tap device. 
builddeps  :
    - haskell-boundedchan
    - haskell-cabal-install
    - haskell-cereal
    - haskell-cryptonite
    - haskell-heaps
    - haskell-memory
    - haskell-monadlib
    - haskell-psqueues
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
